#
# General settings:
#

workspace: /home/kiosan/projects/zee/public/video_stories

#
# Settings for inspection:
#

ffmpeg_get_info: ffmpeg -i <source_file> 2>&1


#
# Settings for rendering-phase
#

audio_extract: ffmpeg -i <source> -ar 44100 -ac 2 -ab 128k <target> 1>/dev/null 2>&1

video_trim: ffmpeg -i <source> -vcodec mjpeg -b 200k -qscale 2 -an -s <width>x<height> -padcolor 000000 -padtop <padding_top> -padbottom <padding_bottom> -r 25 -ss <in> -t <length> -y <target> 1>/dev/null 2>&1

still_video: ffmpeg -loop_input -vframes <frames> -f image2 -i <source> -vcodec mjpeg -b 200k -qscale 1 -an -s <resolution> -r 25 -y <target> 1>/dev/null 2>&1

video_combine: mencoder -forceidx -oac copy -ovc copy -noskip -o <target> <source> 1>/dev/null 2>&1

final_mux: ffmpeg -i <source_video> -i <source_audio> <audio_options> <video_options> <target> 

# 1>/dev/null 2>&1

thumbnail: ffmpeg  -itsoffset -4  -i <source_video> -vcodec mjpeg -vframes 1 -an -f rawvideo -s 120x90 <thumbnail>